// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistrationWeb.Data;

#nullable disable

namespace RegistrationWeb.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231007054731_AddTablesToDatabase")]
    partial class AddTablesToDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistrationWeb.Models.Declaration", b =>
                {
                    b.Property<int>("DeclarationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeclarationId"));

                    b.Property<string>("CapitalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("signeddate")
                        .HasColumnType("datetime2");

                    b.HasKey("DeclarationId");

                    b.ToTable("Declarationtable");
                });

            modelBuilder.Entity("RegistrationWeb.Models.Edu", b =>
                {
                    b.Property<int>("EduId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EduId"));

                    b.Property<int?>("PG")
                        .HasColumnType("int");

                    b.Property<string>("PGCousre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PGUniversity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UG")
                        .HasColumnType("int");

                    b.Property<string>("UGCousre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("software")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tenth")
                        .HasColumnType("int");

                    b.Property<string>("tenthboard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("twelth")
                        .HasColumnType("int");

                    b.Property<string>("twelthboard")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EduId");

                    b.ToTable("Edutable");
                });

            modelBuilder.Entity("RegistrationWeb.Models.PersAss", b =>
                {
                    b.Property<int>("PersAssId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersAssId"));

                    b.Property<string>("Goals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hobbies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sports")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("atMNJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strength")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("weaknesses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersAssId");

                    b.ToTable("PersAsstable");
                });

            modelBuilder.Entity("RegistrationWeb.Models.Personal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personaltable");
                });

            modelBuilder.Entity("RegistrationWeb.Models.PrevEmp", b =>
                {
                    b.Property<int>("PrevEmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrevEmpId"));

                    b.Property<string>("CTC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContRepManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HREmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HRMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HRName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepManager")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrevEmpId");

                    b.ToTable("PrevEmptable");
                });
#pragma warning restore 612, 618
        }
    }
}
